apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-db
  namespace: default
spec:
 chart:
   spec:
     chart: mongodb
     sourceRef:
       kind: HelmRepository
       name: bitnami
     version: ">=2.7.0"
 interval: 1m0s
values:
  --set auth.rootPassword=secretpassword,auth.username=my-user,auth.password=my-password,auth.database=my-database
