apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-hub
  namespace: default
spec:
 chart:
   spec:
     chart: jupyterhub
     sourceRef:
       kind: HelmRepository
       name: bitnami
     version: ">=2.7.0"
 interval: 1m0s
values:
